# Generated by Django 5.0.4 on 2024-04-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('cover_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Books_rent_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('rent_days', models.IntegerField()),
            ],
        ),
    ]
